utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamSelector.java, utam-compiler/src/main/java/utam/compiler/helpers/ClickableActionType.java, utam-compiler/src/main/java/utam/compiler/helpers/ElementContext.java, utam-compiler/src/main/java/utam/compiler/helpers/MatcherType.java, utam-compiler/src/main/java/utam/compiler/representation/ElementMethod.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamArgument_Tests.java, utam-compiler/src/test/java/utam/compiler/helpers/MethodContextTests.java, utam-compiler/src/test/java/utam/compiler/representation/InterfaceMethodTests.java, utam-core/src/main/java/utam/core/declarative/representation/AnnotationProvider.java, utam-core/src/main/java/utam/core/framework/element/ElementLocationChain.java, utam-core/src/main/java/utam/core/selenium/element/ElementAdapter.java
This reduces the need to suppress unchecked assignment warnings.
=> chore: Replace Collections.EMPTY_LIST with Collections.emptyList()

utam-core/src/main/java/utam/core/driver/Document.java, utam-core/src/main/java/utam/core/framework/base/RootPageObject.java, utam-core/src/main/java/utam/core/framework/consumer/UtamLoader.java, utam-core/src/main/java/utam/core/framework/consumer/UtamLoaderImpl.java, utam-core/src/main/java/utam/core/framework/element/DocumentObject.java, utam-core/src/test/java/utam/core/framework/consumer/UtamLoaderTests.java, utam-core/src/test/java/utam/core/framework/element/DocumentObjectTests.java
Subject of this PR is to provide test writer ability to check presence of the root PO, for example modal.
- added public API Document.containsObject(type)
- added public API UtamLoader.getDocument()
- unit tests
from test can be used like this: `loader.getDocument().containsObject(MyRootPageObject.class)`
=> ability to check presence of root Page Object

utam-core/src/main/java/utam/core/selenium/utilities/WebDriverSimulator.java, utam-core/src/test/java/utam/core/selenium/utilities/TestObjectFactory.java
WebElementInfo.setFocus will let developer set focus to an element in unit tests.
=> Creating methods to enable focus setting for Unit Tests in the simulator

utam-compiler/src/main/java/utam/compiler/grammar/UtamSelector.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamSelector_Tests.java
this allows to parametrize container selector
```json
{
"elements" : [
{
"name" : "panel",
"type" : "container",
"public" : true,
"selector": {
"css": "%s",
"args": [
{
"name": "selector",
"type": "string"
}
]
}
}
]
}
```
=> @W-9282057 fix number of args for selector

utam-core/src/main/java/utam/core/element/FrameElement.java, utam-core/src/main/java/utam/core/framework/base/FrameElementImpl.java, utam-core/src/main/java/utam/core/framework/element/DocumentObject.java, utam-core/src/test/java/utam/core/framework/base/FrameElementTests.java, utam-core/src/test/java/utam/core/selenium/element/DriverAdapterTests.java
hide FrameElement.getFrameElement() to avoid misuse from test like 
`getMyFrame().getFrameElement().callDirectAPIOfElement()`
=> @W-9794410 hide underlying Element from Frame

utam-core/src/main/java/utam/core/selenium/appium/LocatorUIAutomator.java, utam-core/src/test/java/utam/core/selenium/appium/LocatorUiAutomatorTests.java
We already support this locator - "new UiScrollable(new UiSelector().scrollable(true)).scrollIntoView(resourceId(\"com.salesforce.chatter:id/app_launcher_menu_item\"))"
This fix is to support - "new UiScrollable(new UiSelector().resourceId(\"com.salesforce.fieldservice.app:id/work_view\")).scrollIntoView(new UiSelector().resourceId(\"com.salesforce.chatter:id/app_launcher_menu_item\"))"
UiScrollable can use resourceId or other supported methods.
=> @W-9919770 Bug fix in UIAutomator locator static check

utam-core/src/main/java/utam/core/framework/base/BasePageObject.java, utam-core/src/test/java/utam/core/OutsidePackageProxyTest.java, utam-core/src/test/java/utam/core/framework/base/BasePageObjectTests.java
Fixed the issue (confirmed in mobile repo) and moved tests to different package otherwise issue was not reproducible.
Error for proxy was: 
java.lang.IllegalArgumentException: non-public interfaces from different packages
at java.base/java.lang.reflect.Proxy$ProxyBuilder.mapToModule(Proxy.java:788)
at java.base/java.lang.reflect.Proxy$ProxyBuilder.<init>(Proxy.java:630)
at java.base/java.lang.reflect.Proxy.lambda$getProxyConstructor$1(Proxy.java:426)
at java.base/jdk.internal.loader.AbstractClassLoaderValue$Memoizer.get(AbstractClassLoaderValue.java:329)
at java.base/jdk.internal.loader.AbstractClassLoaderValue.computeIfAbsent(AbstractClassLoaderValue.java:205)
at java.base/java.lang.reflect.Proxy.getProxyConstructor(Proxy.java:424)
at …
=> fix: proxy interface should be public

utam-core/src/main/java/utam/core/framework/element/BasePageElement.java
Updating BasePageElement.click method to handle latest chrome browser javascript error.
New message from chrome browser:  Cannot read properties of undefined (reading 'defaultView')
Previous: javascript error: Cannot read property 'defaultView' of undefined
=> W-10481798 Updating BasePageElement.click method to handle browser error message

utam-compiler/src/main/java/utam/compiler/translator/TranslatorGenerationCommand.java
The feature to add a copyright header to generated files should be accessed through a JSON compiler configuration settings file only, rather than make it available through the command line.
=> feat: Rollback availability of setting copyright via command line

utam-core/src/main/java/utam/core/framework/context/MobilePlatformType.java, utam-core/src/test/java/utam/core/framework/context/MobilePlatformTypeTests.java, utam-core/src/test/java/utam/core/selenium/factory/WebDriverFactoryTests.java
getSessionDetail is from HasSessionDetails which is for JWP protocol only. Therefore, if the test uses W3C protocol, the test will hit getSessionDetail not implement error. In order to handle the test that either uses JWP or W3C protocols, switch to using the more generic getCapabilites to query the device information for screen size and screen density. 
Update the related unit tests accordingly.
=> fix: replace getSessionDetail with more generic getCapabilities to obtain test android device info

utam-core/src/main/java/utam/core/element/BasicElement.java, utam-core/src/main/java/utam/core/element/Element.java, utam-core/src/main/java/utam/core/selenium/element/ElementAdapter.java, utam-core/src/test/java/utam/core/selenium/element/ElementAdapterTests.java
This PR fixes an issue of isFocused not working for elements inside shadow DOM. According to https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/activeElement for elements inside shadowRoot focus is defined by shadowRoot.activeElement and not by document.activeElement
If element has shadowHost, check if current element is same as shadowHost.shadowRoot.activeElement
Corresponding PR for JS https://github.com/salesforce/utam-js/pull/276
=> refactor: ability to check active element inside shadow

utam-core/src/main/java/utam/core/framework/base/PageObjectsFactoryImpl.java, utam-core/src/main/java/utam/core/selenium/appium/MobileDriverAdapter.java
This is applicable for only mobile webviews. As per the current implementation, context is switched to webview for all web page objects implicitly when bootsrapped. This involves multiple commands to get available contexts, switch to webview context and validate the title.
For child page objects, since the context is already set via root, this is an overhead. This change does a root PO check thereby avoiding repeated context switch and improves the speed of the mobile tests involving webviews.
utam-js PR https://github.com/salesforce/utam-js/pull/295
=> refactor: context switching for only root POs

utam-compiler/src/main/java/utam/compiler/lint/LintingConfigJson.java, utam-compiler/src/test/java/utam/compiler/lint/LintingRuleTests.java
Config parameter was moved outside "lint" while doing sarif work, see https://utam.dev/guide/java-guide#compiler-setup
Docs fixed as well, see https://github.com/salesforce-experience-platform/utam-docs/pull/389
=> fix: remove redundant property from lint config

utam-compiler/src/main/java/utam/compiler/helpers/TranslationContext.java, utam-compiler/src/main/java/utam/compiler/representation/JavadocObject.java, utam-compiler/src/main/java/utam/compiler/translator/DefaultTranslatorConfiguration.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamRootDescriptionTests.java, utam-compiler/src/test/java/utam/compiler/translator/DefaultTranslatorConfigurationTests.java, utam-compiler/src/test/java/utam/compiler/translator/JsonCompilerConfigTests.java, utam-core/src/main/java/utam/core/declarative/translator/TranslatorConfig.java
When the date and time is used as the version, the output files are rarely up-to-date. The outputs should only change when the declared inputs change.
Work: @W-12992962
=> fix: remove timestamps from version javadoc tag

utam-compiler/src/main/java/utam/compiler/lint/LintingConfigJson.java, utam-compiler/src/test/java/utam/compiler/lint/LintingConfigJsonTests.java, utam-compiler/src/test/resources/lint/changeDefaultConfig/config.json, utam-compiler/src/test/resources/lint/changeGlobalRules/config.json, utam-compiler/src/test/resources/lint/report/config.json, utam-compiler/src/test/resources/lint/report/test.utam.json, utam-compiler/src/test/resources/lint/sarif/config.json
if `writeSarifReport` is not set in compiler config, skip writing lint report
=> fix: do not write linting report by default

utam-compiler/src/main/java/utam/compiler/grammar/UtamMetadata.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/java/utam/compiler/lint/JsonLintRulesConfig.java, utam-compiler/src/main/java/utam/compiler/lint/LintingConfigJson.java, utam-compiler/src/main/java/utam/compiler/lint/LintingRuleImpl.java, utam-compiler/src/main/java/utam/compiler/lint/PageObjectLintingImpl.java, utam-compiler/src/main/resources/errors.config.json, utam-compiler/src/main/resources/rules.config.json, utam-compiler/src/test/java/utam/compiler/lint/LintingRuleTests.java, utam-compiler/src/test/java/utam/compiler/lint/SarifConverterTests.java, utam-compiler/src/test/java/utam/compiler/translator/TranslatorGenerationCommandTests.java, utam-compiler/src/test/resources/lint/metadata/pageWithEmptyMetadataProperty.json, utam-compiler/src/test/resources/lint/metadata/pageWithInvalidMetadataProperty.json, utam-compiler/src/test/resources/lint/metadata/pageWithMetadata.json, utam-compiler/src/test/resources/lint/metadata/pageWithMissingMetadataProperty.json, utam-compiler/src/test/resources/lint/metadata/pageWithoutMetadata.json, utam-compiler/src/test/resources/lint/metadata/presence.config.json, utam-compiler/src/test/resources/lint/metadata/structure.config.json, utam-core/src/main/java/utam/core/declarative/lint/PageObjectLinting.java
This PR adds a new rule for linting the metadata field (disabled by default, because it's an optional field), and can be configured in the compiler config with the following JSON:
```json
{
"lint": {
"requiredMetadata": {
"violation": "warning",
"exclude": [],
"additionalConfiguration": {
"requiredProperties": [
{
"name": "foo"
},
{
"name": "bar",
"values": [ "baz", "quux", "corge" ]
}
]
}
}
}
}
```
The `requiredMetadata` property without any `additionalConfiguration` entries will simply check for the presence of the `metadata` property in each page object. Within `additionalConfiguration`, the user is able to specify a `requiredProperties` list that indicates the properties that must be present in the metadata object.
An object in the `requiredProperties` array with only a `name` field …
=> feat: Add configurable lint rule for metadata object

utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/java/utam/compiler/lint/PageObjectLintingImpl.java, utam-compiler/src/test/java/utam/compiler/lint/LintingRuleTests.java, utam-compiler/src/test/resources/lint/rules/listSelectorWithFilters.json
This change updates the lint rule for duplicate selectors in the same page object to allow duplicates in element definitions under the following circumstances:
* One element is a list, and the other is not
* Two elements are lists, but one contains a filter and the other does not
* Two elements are lists and both contain filters, but they filter on different apply methods
* Two elements are lists and both contain filters on the same method, but use different matcher types
=> feat: update duplicate selector lint rule for lists

utam-compiler/src/main/java/utam/compiler/grammar/UtamComposeMethod.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/helpers/TranslationContext.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamElementLoadTests.java, utam-compiler/src/test/java/utam/compiler/helpers/TranslationContextTests.java, utam-compiler/src/test/java/utam/compiler/translator/DefaultTranslatorRunnerTests.java, utam-compiler/src/test/resources/validate/wait/waitForNameCollisionPrivate.json, utam-compiler/src/test/resources/validate/wait/waitForNameCollisionPublic.json
The `wait` feature can generate names that collide with user-provided names.
(current, working as expected) An element named `test` with `wait:true` and `public:true` _**will**_ generate a public getter named `waitForTest`. This throws a compile error.
(changed, was broken) An element named `test` with `wait:true` and `public:false` **_will not_** generate a public getter named `waitForTest`. This should not throw an error if a user defines a method named `waitForTest`.
Code review notes: This is branched off the formatting PR.
QA notes: Look the JSON PO files in the PR to verify they compile as expected.
=> fix(compiler): name collisions on waits

utam-compiler/src/main/java/utam/compiler/grammar/JsonDeserializer.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/resources/errors.config.json, utam-compiler/src/test/java/utam/compiler/translator/DefaultTranslatorRunnerTests.java
Updates the compiler's error message to align with the JS compiler by providing a better error when the generated `waitFor` name has a collision with a user-defined method name.
Continues the work done in #207 .
The fix pushes a list of methods along so when we generate the `waitFor` function name, we can check if it would be unique.
=> fix(compiler): change waitFor 504 error to 505

utam-compiler/src/main/java/utam/compiler/lint/LintingConfigJson.java, utam-compiler/src/main/java/utam/compiler/lint/LintingRuleImpl.java, utam-compiler/src/main/resources/errors.config.json, utam-compiler/src/main/resources/rules.config.json, utam-compiler/src/test/java/utam/compiler/lint/LintingRuleTests.java, utam-compiler/src/test/java/utam/compiler/lint/SarifConverterTests.java, utam-compiler/src/test/resources/lint/metadata/presence.config.json, utam-compiler/src/test/resources/lint/metadata/structure.config.json
After implementing ability for custom and container to have nested elements, we no longer consider multiple shadow boundaries a violation.
Documentation https://github.com/salesforce-experience-platform-emu/utam-docs/pull/985
=> feat: disable linting violation for  multiple boundaries

utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/representation/ContainerMethod.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamElementContainerTests.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamElementCustomTests.java, utam-compiler/src/test/resources/container/containerNullable.json, utam-compiler/src/test/resources/generated/container/containerNullable.utam.json, utam-core/src/main/java/utam/core/framework/base/BasePageObject.java, utam-core/src/main/java/utam/core/framework/base/ContainerElementImpl.java, utam-core/src/main/java/utam/core/framework/base/ContainerElementPageObject.java, utam-core/src/main/java/utam/core/framework/consumer/ContainerElement.java, utam-core/src/test/java/utam/core/framework/base/ContainerElementPageObjectTests.java, utam-core/src/test/java/utam/core/framework/base/ContainerElementTests.java, utam-core/src/test/java/utam/core/framework/base/PageObjectTests.java
Before change "nullable" was not supported, after the change if nullable is set to true, generated code will be
```java
return this.container(root).nullable(true).build().load(pageObjectType, locator);
// if expand shadow is also true
return this.container(root).expandShadow(true).nullable(true).build().load(pageObjectType, locator);
```
Docs update https://github.com/salesforce-experience-platform-emu/utam-docs/pull/1130
=> feat: support for nullable flag in container element
