salesforce/utam-java

utam-core/src/test/java/utam/core/framework/consumer/TestLoaderConfigDefault.java, utam-core/src/test/java/utam/core/framework/consumer/TestLoaderConfigPageObjectProfile.java, utam-core/src/test/java/utam/core/framework/consumer/UtamLoaderConfigTests.java, utam-core/src/test/java/utam/core/framework/consumer/UtamLoaderTests.java, utam-core/src/test/resources/default_impl_config.properties, utam-core/src/test/resources/module1_custom_one_config.properties
Adding couple unit tests for use cases specific for mobile team
=> @W-9612281 add unit tests

utam-core/src/main/java/utam/core/framework/consumer/JsonLoaderConfig.java, utam-core/src/test/java/utam/core/framework/consumer/JsonLoaderConfigTests.java
fix for when resources from transitive dependencies were not loaded correctly
=> @W-9282057 bugfix for utam loader resources

utam-compiler/src/main/java/utam/compiler/grammar/UtamSelector.java, utam-compiler/src/main/java/utam/compiler/translator/DefaultSourceConfiguration.java, utam-compiler/src/main/java/utam/compiler/translator/JsonCompilerConfig.java, utam-compiler/src/main/java/utam/compiler/translator/StringValueProfileConfig.java, utam-compiler/src/main/java/utam/compiler/translator/TranslationTypesConfigJava.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamMethod_AbstractTests.java, utam-compiler/src/test/java/utam/compiler/translator/DefaultTranslatorRunnerTests.java, utam-compiler/src/test/java/utam/compiler/translator/JsonCompilerConfigTests.java, utam-compiler/src/test/java/utam/compiler/translator/StringValueProfileConfigTests.java, utam-compiler/src/test/java/utam/compiler/translator/TranslationTypesConfigJavaTests.java, utam-compiler/src/test/java/utam/compiler/translator/TranslatorGenerationCommandTests.java, utam-compiler/src/test/resources/nonamespaces.config.json, utam-compiler/src/test/resources/utam.config.json
Align properties and format with https://rfcs.lwc.dev/rfcs/utam/2021-07-15-compiler-config
=> @W-9649972 JSON compiler config align with RFC

utam-core/src/main/java/utam/core/selenium/appium/LocatorUIAutomator.java, utam-core/src/test/java/utam/core/framework/base/ElementMarkerTests.java, utam-core/src/test/java/utam/core/framework/base/PageMarkerTests.java, utam-core/src/test/java/utam/core/selenium/appium/LocatorUiAutomatorTests.java
@helenren @lizaiv77 could you please review? This is required to use Android UIAutomator locator with 'UIScrollable' class to scroll to an element that is not in view.
=> @W-9806702 Allow UIScrollable class in Android UIAutomator locator

utam-compiler/src/main/java/utam/compiler/helpers/TouchableActionType.java, utam-compiler/src/test/java/utam/compiler/helpers/TouchableActionTypeTests.java, utam-core/src/main/java/utam/core/element/Element.java, utam-core/src/main/java/utam/core/element/Touchable.java, utam-core/src/main/java/utam/core/framework/element/BasePageElement.java, utam-core/src/main/java/utam/core/selenium/appium/MobileDriverUtils.java, utam-core/src/main/java/utam/core/selenium/appium/MobileElementAdapter.java, utam-core/src/main/java/utam/core/selenium/element/ElementAdapter.java, utam-core/src/test/java/utam/core/framework/element/BasePageElementTests.java, utam-core/src/test/java/utam/core/framework/element/ExpectationsImplTests.java, utam-core/src/test/java/utam/core/selenium/appium/MobileElementAdapterTests.java, utam-core/src/test/java/utam/core/selenium/element/ElementAdapterTests.java
@lizaiv77 @helenren please review.
=> @W-9643768 updates to flick method to bound the flick co-ordinates

utam-core/src/main/java/utam/core/element/DragAndDropOptions.java, utam-core/src/main/java/utam/core/framework/element/BasePageElement.java, utam-core/src/main/java/utam/core/selenium/element/ElementAdapter.java, utam-core/src/test/java/utam/core/selenium/element/ElementAdapterTests.java
Use standard Selenium Actions.dragAndDrop instead custom sequence when offset is 0
Test with CDP UI tests in java recipes
=> add standard selenium drag and drop

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/feature_request.md
This PR adds a set of templates for bug and feature request for the repository, it also disable blank issues to the only entry point for issues are the templates
=> @W-10311469 Add github issue templates

.gitignore, pom.xml, utam-compiler/pom.xml, utam-compiler/src/test/resources/generated/basic/testBasicTypes.utam.json, utam-compiler/src/test/resources/generated/compiler.config.json, utam-compiler/src/test/resources/generated/custom/testCustomTypes.utam.json
Ability to generate PO as part of unit tests for compiler. Actual tests will be added later.
=> add page objects compilation to test phase

pom.xml, utam-core/pom.xml, utam-core/src/main/java/utam/core/framework/UtamLogger.java, utam-core/src/test/java/utam/core/framework/UtamLoggerTests.java
This commit will remove the dependency on log4j, taking advantage of the existing
slf4j dependency.
=> fix (utam-core): Update logger

utam-core/src/main/java/utam/core/selenium/element/DriverAdapter.java, utam-core/src/test/java/utam/core/selenium/element/DriverAdapterTests.java
Align with utam-js: waitFor should ignore any exception, not only from WebDriver
=> Driver.waitFor should ignore any exception

utam-core/src/main/java/utam/core/selenium/element/DriverAdapter.java, utam-core/src/main/java/utam/core/selenium/element/ShadowRootElementAdapter.java
Tested with utam-java-recipes records tests
=> fix: add implicit wait for shadow root

utam-compiler/src/main/java/utam/compiler/grammar/JsonDeserializer.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamRootDescription.java, utam-compiler/src/main/java/utam/compiler/helpers/TranslationContext.java, utam-compiler/src/main/java/utam/compiler/translator/DefaultSourceConfiguration.java, utam-compiler/src/main/java/utam/compiler/translator/DefaultTranslatorConfiguration.java, utam-compiler/src/main/java/utam/compiler/translator/JsonCompilerConfig.java, utam-compiler/src/main/java/utam/compiler/translator/TranslatorGenerationCommand.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamRootDescriptionTests.java, utam-compiler/src/test/java/utam/compiler/translator/DefaultSourceConfigurationTests.java, utam-compiler/src/test/java/utam/compiler/translator/DefaultTranslatorConfigurationTests.java, utam-compiler/src/test/java/utam/compiler/translator/JsonCompilerConfigTests.java, utam-compiler/src/test/java/utam/compiler/translator/TranslatorMockUtilities.java, utam-compiler/src/test/resources/config/nofields.json, utam-compiler/src/test/resources/config/utam.config.json, utam-compiler/src/test/resources/generated/compiler.config.json, utam-core/src/main/java/utam/core/declarative/translator/TranslatorConfig.java, utam-core/src/main/java/utam/core/declarative/translator/TranslatorSourceConfig.java
generated:
```java
/**
* created from JSON resources/generated/comments/verbose.utam.json
*
* @author UTAM
* @since Spring'22
*/
public interface Verbose extends PageObject {
```
=> feat: add version and json to javadoc

README.md
- added badge for MavenCentral with the latest version
- License badge
- two Snyk badges
=> docs(readme): add badges to the readme

utam-compiler/src/main/java/utam/compiler/grammar/JsonDeserializer.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamArgument.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamComposeMethod.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamProfile.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamShadowElement.java, utam-compiler/src/main/resources/errors.config.json, utam-compiler/src/test/java/utam/compiler/grammar/UtamPageObjectInterfaceTests.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamPageObject_Tests.java
Alignment with JS: no impact, just fixing validations to not allow "platform" inside interface
=> fix: add validation and test for interface properties

utam-compiler/src/main/java/utam/compiler/grammar/UtamArgument.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamElementFilter.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamMethodActionApply.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamMethodActionGetter.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/java/utam/compiler/helpers/ElementContext.java, utam-compiler/src/main/java/utam/compiler/types/BasicElementInterface.java, utam-compiler/src/test/java/utam/compiler/guardrails/PageObjectValidationTests.java, utam-compiler/src/test/java/utam/compiler/guardrails/ValidationUtilitiesTests.java, utam-compiler/src/test/java/utam/compiler/helpers/ElementContextTests.java, utam-compiler/src/test/java/utam/compiler/helpers/TranslationContextTests.java, utam-compiler/src/test/resources/generated/compiler.config.json, utam-compiler/src/test/resources/generated/container/testContainer.utam.json, utam-compiler/src/test/resources/generated/frame/testFrame.utam.json
When frame was scoped inside private element, code would not compile because getter was not generated.
Code generated from this JSON would not compile:
```json
"elements": [
{
"name": "scopePrivate",
"selector": {
"css": "scope"
},
"elements": [
{
"public": true,
"type": "frame",
"name": "scopedFrame",
"selector": {
"css": "scopedFrame"
}
}
]
```
Generated code was correct but would not compile because getter `getScopePrivateElement()` was not generated for element marked as private.
```java
public final FrameElement getScopedFrame() {
BasicElement scopePrivate = this.getScopePrivateElement();
return basic(scopePrivate, this.scopedFrame).buildFrame();
}
```
TBD - we should consider removing logic "we should generate method only if it's public or if we use the method"
=> fix: private scope element for frame did not have getter

utam-compiler/src/main/java/utam/compiler/grammar/UtamMethodActionApply.java, utam-compiler/src/main/java/utam/compiler/helpers/ElementContext.java, utam-compiler/src/main/java/utam/compiler/helpers/TranslationContext.java, utam-compiler/src/main/java/utam/compiler/representation/ElementMethod.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamElement_BasicTests.java, utam-compiler/src/test/java/utam/compiler/grammar/UtamMethodActionApplyTests.java, utam-compiler/src/test/java/utam/compiler/helpers/ElementContextTests.java, utam-compiler/src/test/java/utam/compiler/representation/ElementMethodTests.java, utam-compiler/src/test/resources/compose/apply/navigationElement.json, utam-compiler/src/test/resources/generated/mobile/applyNavigationDocument.utam.json, utam-compiler/src/test/resources/validate/basic_element/navigationName.json, utam-core/src/main/java/utam/core/driver/Driver.java, utam-core/src/main/java/utam/core/driver/Navigation.java, utam-core/src/main/java/utam/core/framework/base/BasePageObject.java, utam-core/src/main/java/utam/core/framework/base/PageObjectsFactoryImpl.java, utam-core/src/main/java/utam/core/framework/consumer/UtamLoader.java, utam-core/src/main/java/utam/core/framework/consumer/UtamLoaderImpl.java, utam-core/src/main/java/utam/core/framework/element/NavigationImpl.java, utam-core/src/main/java/utam/core/selenium/appium/MobileDriverAdapter.java, utam-core/src/main/java/utam/core/selenium/element/DriverAdapter.java, utam-core/src/test/java/utam/core/MockUtilities.java, utam-core/src/test/java/utam/core/framework/base/PageObjectTests.java, utam-core/src/test/java/utam/core/framework/consumer/UtamLoaderTests.java, utam-core/src/test/java/utam/core/framework/element/NavigationTests.java, utam-core/src/test/java/utam/core/selenium/appium/MobileDriverAdapterTests.java, utam-core/src/test/java/utam/core/selenium/element/DriverAdapterTests.java
- add Navigation object with back and forward methods
- add ability to use `"element" : "navigation" to the grammar
=> feat: add navigation object

utam-core/src/main/java/utam/core/framework/element/NavigationImpl.java
Handle the case where a window is closed, meaning there is no currently focused window, and the URL specified to switch to does not exist. The algorithm was not handling the case where there was no currently focused window.
=> fix: Update switchToWindow error case

utam-compiler/src/main/java/utam/compiler/translator/DefaultTranslatorRunner.java, utam-compiler/src/main/java/utam/compiler/translator/JsonCompilerOutput.java, utam-compiler/src/test/java/utam/compiler/translator/DefaultTranslatorRunnerTests.java, utam-compiler/src/test/java/utam/compiler/translator/JsonCompilerOutputTests.java
Fix: we do not want to write file with empty dependencies config
=> fix: skip creating empty dependencies config

utam-compiler/src/main/java/utam/compiler/lint/LintingConfigJson.java, utam-compiler/src/test/java/utam/compiler/lint/LintingConfigJsonTests.java, utam-compiler/src/test/resources/lint/throwConfigPass/config.json, utam-compiler/src/test/resources/lint/throwConfigPass/test.utam.json
See docs changes for linting in https://github.com/salesforce-experience-platform-emu/utam-docs/pull/733
Remove parameters `writeSarifReport` and `printToConsole`, the only output is now SARIF report
=> feat: linting changes for sarif

utam-compiler/src/main/java/utam/compiler/diagnostics/ValidationUtilities.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamArgument.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamComposeMethod.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamElement.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamMethod.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamMethodActionUtility.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamMethodActionWaitFor.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamPageObject.java, utam-compiler/src/main/java/utam/compiler/grammar/UtamProfile.java, utam-compiler/src/main/java/utam/compiler/helpers/ElementContext.java, utam-compiler/src/main/java/utam/compiler/helpers/MethodContext.java, utam-compiler/src/main/java/utam/compiler/representation/ComposeMethod.java, utam-compiler/src/main/java/utam/compiler/representation/CustomElementMethod.java, utam-compiler/src/main/java/utam/compiler/representation/InterfaceMethod.java, utam-compiler/src/main/java/utam/compiler/translator/DefaultTargetConfiguration.java, utam-compiler/src/main/java/utam/compiler/translator/DefaultTranslatorConfiguration.java, utam-compiler/src/main/java/utam/compiler/translator/JsonCompilerConfig.java, utam-compiler/src/main/java/utam/compiler/translator/TranslatorGenerationCommand.java, utam-compiler/src/test/java/utam/compiler/representation/PageObjectValidationTestHelper.java, utam-core/src/main/java/utam/core/selenium/element/Rect.java, utam-core/src/main/java/utam/core/selenium/utilities/WebDriverSimulator.java, utam-core/src/test/java/utam/core/selenium/utilities/TestObjectFactory.java
While releasing maven reported bunch of Javadoc issues, fixed
Then ran inspection (static analysis) and address some of the reported issues that seem harmless.
=> chore: apply javadocs warnings and inspection issues

pom.xml, utam-core/src/main/java/utam/core/framework/context/MobilePlatformType.java, utam-core/src/main/java/utam/core/selenium/appium/MobileDriverAdapter.java, utam-core/src/main/java/utam/core/selenium/appium/MobileDriverUtils.java, utam-core/src/main/java/utam/core/selenium/appium/MobileElementAdapter.java, utam-core/src/test/java/utam/core/MockUtilities.java, utam-core/src/test/java/utam/core/framework/context/MobilePlatformTypeTests.java, utam-core/src/test/java/utam/core/selenium/appium/MobileDriverAdapterTests.java, utam-core/src/test/java/utam/core/selenium/appium/MobileElementAdapterTests.java, utam-core/src/test/java/utam/core/selenium/factory/WebDriverFactoryTests.java
Note: This updates to Selenium 4.10.0, as that's the version that Core is being updated to for now. Yes, we want to update to the latest, but we will need to push that along internally before allowing it here.
=> feat: Update to Selenium 4.10 and Appium Java client 8.5.0

.github/workflows/ci-build.yml
Enables CI via GitHub Actions, obsoleting CircleCI.
=> feat: Create GitHub Actions ci-build.yml
